main: net.euphoriamc.essentialshomegui.EssentialsHomeGUI
name: EssentialsHomeGUI
version: ${project.version}
author: wsman217
api-version: "1.14"

commands:
  editgui:
    description: "Edit the gui"
  renametest:
    description: "test"

permissions:
  EssentialsHomeGUI.EditGUI:
    default: op
    description: "Permission to edit the gui"